/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./details.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "on-primary-container": "#64000d",
        "primary-fixed": "#ffdad7",
        "secondary-fixed": "#9cf0ff",
        "on-background": "#e5e2e3",
        "primary-fixed-dim": "#ffb3af",
        "tertiary-fixed": "#e2e2e2",
        "surface-container": "#201f20",
        "on-primary-fixed": "#410005",
        "tertiary-fixed-dim": "#c6c6c7",
        "tertiary": "#c6c6c7",
        "surface-dim": "#131314",
        "on-error": "#690005",
        "secondary": "#bdf4ff",
        "on-primary-fixed-variant": "#91081a",
        "secondary-fixed-dim": "#00daf3",
        "surface": "#131314",
        "on-surface-variant": "#e1bebc",
        "secondary-container": "#00e3fd",
        "primary-container": "#ff5f5f",
        "on-tertiary": "#2f3131",
        "on-secondary": "#00363d",
        "surface-container-lowest": "#0e0e0f",
        "on-secondary-fixed": "#001f24",
        "inverse-surface": "#e5e2e3",
        "surface-variant": "#353436",
        "background": "#131314",
        "surface-bright": "#3a393a",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#454747",
        "outline": "#a98987",
        "on-primary": "#68000e",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#b3272e",
        "on-tertiary-container": "#2d2f2f",
        "inverse-on-surface": "#313031",
        "surface-container-high": "#2a2a2b",
        "on-secondary-fixed-variant": "#004f58",
        "on-surface": "#e5e2e3",
        "surface-container-highest": "#353436",
        "primary": "#ffb3af",
        "surface-container-low": "#1c1b1c",
        "on-secondary-container": "#00616d",
        "surface-tint": "#ffb3af",
        "tertiary-container": "#959696",
        "outline-variant": "#59413f",
        "on-tertiary-fixed": "#1a1c1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "48px",
        "sm": "16px",
        "xs": "8px",
        "md": "24px",
        "grid-gutter": "24px",
        "base": "4px",
        "lg": "32px",
        "container-margin": "64px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "headline-lg": ["Inter"],
        "title-lg": ["Inter"],
        "display-xl": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "500" }],
        "display-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
